export enum GeneroMusical {
    Axe = 'Axé',
    Blues = "Blues",
    BossaNova = 'Bossa Nova',
    Chillout = 'Chillout',
    ClassicRock = 'Classic Rock',
    Classico = 'Clássico',
    Country = 'Country',
    Dance = 'Dance',
    Eletronica = 'Eletronica',
    Forro = 'Forró',
    Funk = 'Funk',
    HardRock = 'Hard Rock',
    HeavyMetal = 'Heavy Metal',
    Infantil = 'Infantil',
    Jazz = 'Jazz',
    MPB = 'MPB',
    NewAge = 'New Age',
    Samba = 'Samba',
    Pagode = 'Pagode'
}